# Generated by Django 5.0 on 2024-01-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_source_description_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='post_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
