# Generated by Django 5.0 on 2024-01-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_source_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='instagram_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='source',
            name='vk_published',
            field=models.BooleanField(default=False),
        ),
    ]
