# Generated by Django 5.0 on 2024-01-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_source_instagram_published_source_vk_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
